version: '3.5'

services:
  postgres:
    restart: always
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
    image: postgres:alpine3.18
    volumes:
      # if you want mount home directory 1. uncomment 15 row and the last row, 2. comment 16 row
      # - db_data:/var/lib/postgresql/data
      - ./src/db/data/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=msk9199625687@yandex.ru
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - '5050:5050'
    image: dpage/pgadmin4:latest
  php:
    container_name: php
    image: php:7.4-fpm
    volumes:
      - './php:/app/php'
  nginx:
    container_name: nginx
    ports:
      - '80:80'
    image: nginx:alpine3.18
    volumes:
      - './nginx/html:/app/html'
      - './php:/app/php'
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
  nest:
    restart: always
    build: .
    ports:
      - '4000:8080'
    environment:
      - PORT=8080
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=Intranet
      - POSTGRES_PASSWORD=root
      - POSTGRES_PORT=5432
    depends_on:
      - postgres
# volumes:
#   db_data:
