version: '2'
services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    hostname: localhost
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  postgres:
    restart: always
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
    image: postgres:alpine3.18
    volumes:
      - db_data:/var/lib/postgresql/data
      # - ./src/db/data/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=msk9199625687@yandex.ru
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - '5050:5050'
    image: dpage/pgadmin4:latest
  # gateway:
  #   restart: always
  #   build: ./gateway
  #   ports:
  #     - '4000:8080'
  #   environment:
  #     - PORT=8080
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=Intranet
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_PORT=5432
  #   depends_on:
  #     - postgres
  #     - redis
  #     - kafka
  # pdn:
  #   restart: always
  #   build: ./pdn
  #   environment:
  #     - PORT=8080
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=Intranet
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_PORT=5432
  #   depends_on:
  #     - postgres
  #     - kafka
volumes:
  kafka_data:
    driver: local
  redis_data:
    driver: local
  db_data:
    driver: local
